### ISSUE TITLE
Thanks but...

### ISSUE THREAD

**Issue by glyn** [daaain/SmileBankStatementToCSV#2]
It appears that Smile now, at last, provide an export to CSV function. Alleluia!

Go to the account in question, then the transactions tab, then click the "Export to File" button to download a CSV. Apparently this can export up to 13 months of transactions in one go. Goodbye screen-scraping?

**Comment by daaain** [comment]
Right, and also I haven't used or updated the script in a while so the DOM might have very well changed in the meanwhile.

Will put a deprecation notice in the readme and leave the project here for posterity.
